[package]
name = "experimental-rts"
version = "0.1.0"
authors = ["Nehliin <oskar.d.nehlin@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.24"
futures = "0.3"
env_logger = "0.8"
mint = "0.5"
nalgebra = {version = "0.24", features = ["mint"]}
wgpu = "0.6"
log = "0.4"
legion = "0.3"
crevice = "0.5"
tobj = "2"
bytemuck = "1.5"
image = "0.23"
once_cell = "1"
crossbeam-channel = "0.5"
anyhow = "1"

[build-dependencies]
shaderc = "0.7"
glob = "0.3"
rayon = "1"
anyhow = "1"